
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [По умолчанию: true]
	enablecitizenvoices = true
	#По умолчанию, при размещении схемы возле других зданий, уже существующие здания будут показаны как если бы они были 5 уровня, и с синим контуром вокруг. Это можно отключить, установив для него значение false. [По умолчанию: true]
	neighborbuildingrendering = true
	#minecolonies.config.colonyteamborders.comment [По умолчанию: true]
	colonyteamborders = true

