
#General settings
[general]
	#Defines which structures can't be searched with the Structure Compass
	structureBlacklist = [""]
	#Sets the range in which the structure compasses can check for structures [default: 300]
	#Range: > 0
	compassRange = 300
	#Defines if the structure compass should locate unexplored structures [default: false]
	locateUnexplored = false

